"""Build data/Shiftr_Staff_Availability_Oct2026.xlsx from the generated CSVs.

Run generate_staff_data.py first. Uses openpyxl (installed on the ManSci VM).
Lookups, the availability grid and the coverage check are Excel formulas, so
editing an input (e.g. a wage or an availability 1/0) updates the workbook.
"""

import csv
from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.formatting.rule import CellIsRule, FormulaRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
OUT_FILE = DATA_DIR / "Shiftr_Staff_Availability_Oct2026.xlsx"

FONT = "Arial"
BLUE = Font(name=FONT, color="0000FF")             # hardcoded inputs
GREEN = Font(name=FONT, color="008000")            # links to another sheet
BLACK = Font(name=FONT)
BOLD = Font(name=FONT, bold=True)
HEADER_FONT = Font(name=FONT, bold=True, color="FFFFFF")
HEADER_FILL = PatternFill("solid", fgColor="1F3864")
INPUT_FILL = PatternFill("solid", fgColor="FFFF00")
GREY_FILL = PatternFill("solid", fgColor="D9D9D9")
RED_FILL = PatternFill("solid", fgColor="F4B6B6")
AMBER_FILL = PatternFill("solid", fgColor="FCE4A8")
GREEN_FILL = PatternFill("solid", fgColor="C6E0B4")
BLUE_FILL = PatternFill("solid", fgColor="BDD7EE")
THIN = Side(style="thin", color="BFBFBF")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)


def read_csv(name):
    with (DATA_DIR / name).open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def header(ws, row, labels, widths=None):
    for col, label in enumerate(labels, start=1):
        c = ws.cell(row=row, column=col, value=label)
        c.font, c.fill, c.border = HEADER_FONT, HEADER_FILL, BOX
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        if widths:
            ws.column_dimensions[get_column_letter(col)].width = widths[col - 1]


def put(ws, row, col, value, font=BLACK, fmt=None, fill=None):
    c = ws.cell(row=row, column=col, value=value)
    c.font, c.border = font, BOX
    if fmt:
        c.number_format = fmt
    if fill:
        c.fill = fill
    return c


def build_readme(wb):
    ws = wb.active
    ws.title = "README"
    lines = [
        ("Shiftr: staff availability and shift preferences, October 2026", BOLD),
        ("SYNTHETIC DATA. Fictional restaurant, people and wages, generated for the MSIN0023 prototype. Not real data.", Font(name=FONT, bold=True, color="C00000")),
        ("Generated by scripts/generate_staff_data.py (seed 2026) and scripts/export_staff_excel.py.", BLACK),
        ("", BLACK),
        ("The restaurant (team spec)", BOLD),
        ("Small-to-medium Italian restaurant, central London. 50 dining seats (bookings + walk-ins) and a separate 10-stool bar (walk-ins only).", BLACK),
        ("Serves lunch, dinner and bar drinks. Open to customers 11:00-00:00, 7 days a week.", BLACK),
        ("", BLACK),
        ("Sheets", BOLD),
        ("Staff: 40 staff with job title, role, seniority, contract, base wage, max weekly hours, preferred block. Oct available hours is a formula.", BLACK),
        ("NEW HIRES (update 08/10/26): S35 Hugo (Senior CDP), S36 Aisha (CDP), S37 Theo and S39 Nina (Commis Chefs), S38 Kofi (Kitchen Porter), S40 Dev (Floor Supervisor). Added to close the cover gaps against confirmed bookings; S01-S34 are unchanged.", Font(name=FONT, bold=True, color="C00000")),
        ("Shift_Blocks: AM 10:00-16:00 (6 h paid). PM 16:00-00:30 (8.5 h incl. 30-min unpaid break = 8 h paid). Staff arrive 1 h before opening and close 30 min after.", BLACK),
        ("Rules: the legal and staffing rules the optimiser must respect (UK Working Time Regulations), with sources.", BLACK),
        ("Availability: one row per staff x date x block. available is a HARD constraint (1 = can work). preference is SOFT (+1 prefer, 0 neutral, -1 rather not).", BLACK),
        ("Availability_Grid: staff x date view. Both / AM / PM / Off, calculated from the Availability sheet.", BLACK),
        ("Coverage_Check: number of AVAILABLE people per role for every block, against the minimums in row 3 (yellow, editable).", BLACK),
        ("", BLACK),
        ("Colour legend", BOLD),
        ("Blue text = hardcoded input. Black = formula. Green = formula pulling from another sheet. Yellow fill = assumption you can change.", BLACK),
        ("", BLACK),
        ("Built-in scenarios", BOLD),
        ("S04 Marco (head chef) on holiday 19-25 Oct: sous chef and senior CDP must cover every senior-chef block.", BLACK),
        ("S16 Chloe (only senior bartender) on holiday 26-28 Oct: no senior on the bar. S21 Ruth (head waiter) on holiday 1-4 Oct.", BLACK),
        ("S23 Francesca on holiday 26-30 Oct (school half-term), the same week as Chloe: busy Halloween week with two key staff away.", BLACK),
        ("Illness is not included: it is not known in advance, so model it as a what-if.", BLACK),
        ("", BLACK),
        ("Assumptions to verify", BOLD),
        ("Base wages EXCLUDE tronc/tips. They are ESTIMATES for central London from job adverts, all above the GBP 12.71 National Living Wage (GOV.UK, from 1 April 2026).", BLACK),
        ("All staff are assumed to be 18 or over, and 21+ for wage purposes, so the young-worker rules do not apply.", BLACK),
        ("Minimum staffing per block and student weekday-lecture unavailability are team assumptions.", BLACK),
    ]
    for i, (text, font) in enumerate(lines, start=1):
        ws.cell(row=i, column=1, value=text).font = font
    ws.column_dimensions["A"].width = 150


def build_rules(wb):
    ws = wb.create_sheet("Rules")
    header(ws, 1, ["Rule", "Value", "How the optimiser should apply it", "Source / status"],
           [44, 14, 70, 70])
    rules = [
        ("Max average weekly working hours", 48,
         "Cap each person's weekly paid hours at their max_weekly_hours (all contracts <= 48).",
         "Working Time Regulations 1998; GOV.UK 'Maximum weekly working hours'. Average over 17 weeks; opt-out possible but not assumed."),
        ("Minimum daily rest (hours)", 11,
         "At most ONE block per person per day, and no PM followed by AM next day (00:30 to 10:00 is only 9.5 h).",
         "Working Time Regulations 1998; GOV.UK 'Rest breaks at work'."),
        ("Minimum weekly rest (full days off per 7 days)", 1,
         "Each person has at least 1 full day off in every 7 (or 2 in every 14).",
         "Working Time Regulations 1998; GOV.UK 'Rest breaks at work'."),
        ("Rest break if shift > 6 h (minutes)", 20,
         "Built into the PM block as a 30-min unpaid break, so PM pays 8 h.",
         "Working Time Regulations 1998; GOV.UK 'Rest breaks at work'."),
        ("Student max hours per week in term", 20,
         "Student contracts capped at 20 h/week.",
         "Typical limit for degree-level Student visa holders (GOV.UK 'Student visa'). Team assumption that all students are on that limit; check."),
        ("National Living Wage, age 21+ (GBP/h)", 12.71,
         "Every hourly_wage_gbp must be >= this value.",
         "GOV.UK press release 'National Living Wage increases to GBP 12.71 per hour', from 1 April 2026."),
        ("Tips / tronc", "Excluded",
         "Labour cost = base wage x paid hours. Tips are passed to staff, not a restaurant labour cost.",
         "Employment (Allocation of Tips) Act 2023. Team assumption for costing."),
        ("Min managers on every block", 1, "Hard staffing rule.", "Team assumption."),
        ("Min senior chefs on every block", 1, "Hard staffing rule.", "Team assumption."),
        ("Min bartenders on every block", 1, "Bar open 11:00-00:00, walk-ins only.", "Team assumption."),
    ]
    for r, row in enumerate(rules, start=2):
        for c, value in enumerate(row, start=1):
            cell = put(ws, r, c, value, BLUE if c == 2 else BLACK,
                       fill=INPUT_FILL if c == 2 else None)
            cell.alignment = Alignment(wrap_text=True, vertical="top")
    ws.freeze_panes = "A2"


def build_staff(wb, staff, n_avail_rows):
    ws = wb.create_sheet("Staff")
    header(ws, 1, ["staff_id", "first_name", "job_title", "role", "seniority", "contract",
                   "hourly_wage_gbp", "max_weekly_hours", "preferred_block",
                   "Oct available paid hours", "Oct max hours (weekly x 31/7)"],
           [10, 12, 22, 16, 11, 12, 15, 15, 15, 18, 20])
    last = n_avail_rows + 1
    for r, s in enumerate(staff, start=2):
        put(ws, r, 1, s["staff_id"], BLUE)
        put(ws, r, 2, s["first_name"], BLUE)
        put(ws, r, 3, s["job_title"], BLUE)
        put(ws, r, 4, s["role"], BLUE)
        put(ws, r, 5, s["seniority"], BLUE)
        put(ws, r, 6, s["contract"], BLUE)
        put(ws, r, 7, float(s["hourly_wage_gbp"]), BLUE, '"£"#,##0.00')
        put(ws, r, 8, int(s["max_weekly_hours"]), BLUE)
        put(ws, r, 9, s["preferred_block"], BLUE)
        put(ws, r, 10, f"=SUMIFS(Availability!$J$2:$J${last},Availability!$A$2:$A${last},A{r},"
                      f"Availability!$K$2:$K${last},1)", GREEN, "0")
        put(ws, r, 11, f"=ROUND(H{r}*31/7,0)", BLACK, "0")
    ws.cell(row=len(staff) + 3, column=1,
            value="Wages: base pay excl. tronc, ESTIMATES for central London (job adverts); all >= NLW GBP 12.71 "
                  "(GOV.UK, from 1 April 2026). Max weekly hours <= 48 (Working Time Regulations); students <= 20.").font = Font(name=FONT, italic=True)
    ws.freeze_panes = "C2"
    ws.auto_filter.ref = f"A1:K{len(staff) + 1}"


def build_blocks(wb, blocks):
    ws = wb.create_sheet("Shift_Blocks")
    header(ws, 1, ["block", "start", "end", "duration_hours", "unpaid_break_minutes", "paid_hours"],
           [10, 10, 10, 15, 20, 12])
    for r, b in enumerate(blocks, start=2):
        put(ws, r, 1, b["block"], BLUE)
        put(ws, r, 2, b["start"], BLUE)
        put(ws, r, 3, b["end"], BLUE)
        put(ws, r, 4, float(b["duration_hours"]), BLUE, "0.0")
        put(ws, r, 5, int(b["unpaid_break_minutes"]), BLUE)
        put(ws, r, 6, f"=D{r}-E{r}/60", BLACK, "0.0")


def build_availability(wb, rows, n_staff):
    ws = wb.create_sheet("Availability")
    header(ws, 1, ["staff_id", "first_name", "role", "seniority", "date", "weekday",
                   "block", "block_start", "block_end", "paid_hours", "available",
                   "unavailable_reason", "preference"],
           [10, 12, 16, 11, 12, 10, 8, 11, 10, 8, 10, 18, 11])
    s_last = n_staff + 1
    lookup = "INDEX(Staff!${col}$2:${col}${last},MATCH($A{r},Staff!$A$2:$A${last},0))"
    for r, a in enumerate(rows, start=2):
        put(ws, r, 1, a["staff_id"], BLUE)
        put(ws, r, 2, "=" + lookup.format(col="B", last=s_last, r=r), GREEN)
        put(ws, r, 3, "=" + lookup.format(col="D", last=s_last, r=r), GREEN)
        put(ws, r, 4, "=" + lookup.format(col="E", last=s_last, r=r), GREEN)
        put(ws, r, 5, date.fromisoformat(a["date"]), BLUE, "dd-mmm-yyyy")
        put(ws, r, 6, f'=TEXT(E{r},"ddd")', BLACK)
        put(ws, r, 7, a["block"], BLUE)
        put(ws, r, 8, f"=INDEX(Shift_Blocks!$B$2:$B$3,MATCH(G{r},Shift_Blocks!$A$2:$A$3,0))", GREEN)
        put(ws, r, 9, f"=INDEX(Shift_Blocks!$C$2:$C$3,MATCH(G{r},Shift_Blocks!$A$2:$A$3,0))", GREEN)
        put(ws, r, 10, f"=INDEX(Shift_Blocks!$F$2:$F$3,MATCH(G{r},Shift_Blocks!$A$2:$A$3,0))", GREEN)
        put(ws, r, 11, int(a["available"]), BLUE)
        put(ws, r, 12, a["unavailable_reason"] or None, BLUE)
        put(ws, r, 13, int(a["preference"]) if a["preference"] != "" else None, BLUE)
    last = len(rows) + 1
    ws.conditional_formatting.add(f"A2:M{last}", FormulaRule(formula=["$K2=0"], fill=GREY_FILL))
    ws.conditional_formatting.add(f"M2:M{last}", CellIsRule(operator="equal", formula=["1"], fill=GREEN_FILL))
    ws.conditional_formatting.add(f"M2:M{last}", CellIsRule(operator="equal", formula=["-1"], fill=AMBER_FILL))
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:M{last}"
    return last


def build_grid(wb, staff, dates, avail_last):
    ws = wb.create_sheet("Availability_Grid")
    ws.cell(row=1, column=1, value="Who can work when: Both / AM / PM / Off (calculated from the Availability sheet)").font = BOLD
    put(ws, 2, 1, "staff_id", HEADER_FONT, fill=HEADER_FILL)
    put(ws, 2, 2, "role", HEADER_FONT, fill=HEADER_FILL)
    ws.column_dimensions["A"].width = 10
    ws.column_dimensions["B"].width = 16
    for j, d in enumerate(dates, start=3):
        c = put(ws, 2, j, d, HEADER_FONT, "ddd dd", HEADER_FILL)
        c.alignment = Alignment(horizontal="center", text_rotation=90)
        ws.column_dimensions[get_column_letter(j)].width = 6
    rng = "Availability!${c}$2:${c}$" + str(avail_last)
    A, E, G, K = (rng.format(c=x) for x in "AEGK")
    for i, s in enumerate(staff, start=3):
        put(ws, i, 1, f"=Staff!A{i - 1}", GREEN)
        put(ws, i, 2, f"=Staff!D{i - 1}", GREEN)
        for j in range(3, 3 + len(dates)):
            col = get_column_letter(j)
            am = f'SUMIFS({K},{A},$A{i},{E},{col}$2,{G},"AM")'
            pm = f'SUMIFS({K},{A},$A{i},{E},{col}$2,{G},"PM")'
            c = put(ws, i, j, f'=CHOOSE(1+{am}+2*{pm},"Off","AM","PM","Both")', GREEN)
            c.alignment = Alignment(horizontal="center")
    area = f"C3:{get_column_letter(2 + len(dates))}{2 + len(staff)}"
    for text, fill in [("Both", GREEN_FILL), ("AM", BLUE_FILL), ("PM", AMBER_FILL), ("Off", GREY_FILL)]:
        ws.conditional_formatting.add(area, CellIsRule(operator="equal", formula=[f'"{text}"'], fill=fill))
    ws.freeze_panes = "C3"


def build_coverage(wb, dates, avail_last):
    ws = wb.create_sheet("Coverage_Check")
    ws.cell(row=1, column=1, value="Available people per role per block vs minimum (row 3, yellow = editable team assumption). Counts people, not hours.").font = BOLD
    # (label, role, seniority or None, default minimum)
    checks = [
        ("Managers", "Manager", None, 1),
        ("Senior chefs", "Chef", "Senior", 1),
        ("All chefs", "Chef", None, 2),
        ("Kitchen porters", "Kitchen Porter", None, 1),
        ("Bartenders", "Bartender", None, 1),
        ("Servers", "Server", None, 2),
        ("Hosts", "Host", None, 0),
    ]
    header(ws, 2, ["date", "block"] + [c[0] for c in checks] + ["Status"],
           [13, 8] + [12] * len(checks) + [13])
    put(ws, 3, 1, "Minimum", BOLD)
    put(ws, 3, 2, None)
    for j, chk in enumerate(checks, start=3):
        put(ws, 3, j, chk[3], BLUE, fill=INPUT_FILL)
    rng = "Availability!${c}$2:${c}$" + str(avail_last)
    C, D, E, G, K = (rng.format(c=x) for x in "CDEGK")
    r = 4
    for d in dates:
        for block in ("AM", "PM"):
            put(ws, r, 1, d, BLUE, "ddd dd-mmm")
            put(ws, r, 2, block, BLUE)
            for j, (_, role, level, _) in enumerate(checks, start=3):
                f = f'=COUNTIFS({E},$A{r},{G},$B{r},{K},1,{C},"{role}"'
                f += f',{D},"{level}")' if level else ")"
                put(ws, r, j, f, GREEN, "0")
            tests = ",".join(f"{get_column_letter(j)}{r}<{get_column_letter(j)}$3"
                             for j in range(3, 3 + len(checks)))
            put(ws, r, 3 + len(checks), f'=IF(OR({tests}),"SHORTFALL","OK")')
            r += 1
    last = r - 1
    data_area = f"C4:{get_column_letter(2 + len(checks))}{last}"
    ws.conditional_formatting.add(data_area, FormulaRule(formula=["C4<C$3"], fill=RED_FILL))
    status = f"{get_column_letter(3 + len(checks))}4:{get_column_letter(3 + len(checks))}{last}"
    ws.conditional_formatting.add(status, CellIsRule(operator="equal", formula=['"SHORTFALL"'], fill=RED_FILL))
    ws.conditional_formatting.add(status, CellIsRule(operator="equal", formula=['"OK"'], fill=GREEN_FILL))
    s = get_column_letter(3 + len(checks))
    put(ws, last + 2, 1, "Blocks with a shortfall:", BOLD)
    put(ws, last + 2, 3, f'=COUNTIF({s}4:{s}{last},"SHORTFALL")', BOLD)
    ws.freeze_panes = "C4"


def main():
    staff = read_csv("staff.csv")
    blocks = read_csv("shift_blocks.csv")
    rows = read_csv("staff_availability_oct2026.csv")
    dates = sorted({date.fromisoformat(a["date"]) for a in rows})

    wb = Workbook()
    build_readme(wb)
    build_staff(wb, staff, len(rows))
    build_blocks(wb, blocks)
    build_rules(wb)
    avail_last = build_availability(wb, rows, len(staff))
    build_grid(wb, staff, dates, avail_last)
    build_coverage(wb, dates, avail_last)
    wb.calculation.fullCalcOnLoad = True
    wb.save(OUT_FILE)
    print(f"Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
